"use clinet";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/antd-registry";
import { ConfigProvider } from 'antd'
import theme from "@/lib/themes/themeConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "admin page",
  description: "Generated by create next app",
};

import './globals.css'

import PageLayout from "./components/page-layout";

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
  
      <StyledComponentsRegistry>  <ConfigProvider theme={theme}> <PageLayout>{children}</PageLayout> </ConfigProvider></StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
